### ISSUE TITLE
Error on server shutdown/restart

### ISSUE THREAD

**Issue by RWoof** [PlaceholderAPI/PlaceholderAPI#415]
### Issue
> What is the issue? Describe it like you would tell a friend.

PlaceHolderAPI is generating errors when my server is stopped or restarted with either the latest Spigot version 2.10.8 or the latest developer version 2.10.9 DEV 92. (Running Paper 129). Version 2.10.6 works fine. I see the error mentions Ultimate Statistics but the developer of that plugin said it's the latest PAPI causing the error.

Installed Plugins:
Plugins (39): ConditionalCommands*, CoreProtect, dynmap*, Dynmap-Essentials*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, FarmLimiter, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HolographicPlaceholders, IllegalStack, InventoryRollback, Invincible-World-Chests, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Panilla, PlaceholderAPI, PlayerShopGUIPlus, ProtocolLib, ShopGUIPlus, ShopGUIPlusSilkSpawnersBridge, SilkSpawners, Spartan, TimeIsMoney*, UltimateStatistics, Vault, ViaBackwards, ViaVersion, VillagerOptimiser, Vivecraft-Spigot-Extensions, VoidGenerator, WorldEdit

### Expected behaviour
> What should PlaceholderAPI do?

Shut down cleanly without errors.

### Actual behaviour
> What does PlaceholderAPI actually do?

2.10.8 Version: https://pastebin.com/iT6N8zkH
2.10.9 DEV 92 Version: https://pastebin.com/bWc5rUJC

### How to reproduce
> What steps did you made, to get this bug?

1. Install 2.10.8 or 2.10.9 DEV 92 onto Paper 129 server
2. Start up server as normal, things should function.
3. Shut down or restart server, error appears in the console while server is shutting down.

### Installed expansions
> Please list all expansions that are displayed when running `/papi list`

essentials, holographicplaceholders, luckperms, tim, ustats, vault

**Comment by extendedclip** [comment]
Will look into this later today. For now just don't shut down or restart (lol jk)

**Comment by RWoof** [comment]
> Will look into this later today. For now just don't shut down or restart (lol jk)

Lol no worries :D I've rolled back to the older version now to keep things running smoothly until things update. Thanks for checking into it!

**Comment by extendedclip** [comment]
Should be fixed in build 101 a1d69cd25fb7c51c395ecf0d0608d4aa750a33b3

**Comment by extendedclip** [comment]
Report back if it is resolved for you. So far 3 of us have tested and it seems to be good. I’ll wait to close until confirmation.

**Comment by RWoof** [comment]
Thanks for the update, sorry it took so long to test. I receive the following error on shutdown/restart with version 101:

https://pastebin.com/EewDzjJ5

**Comment by Andre601** [comment]
> Thanks for the update, sorry it took so long to test. I receive the following error on shutdown/restart with version 101:
> 
> https://pastebin.com/EewDzjJ5

Hey.
Looking at the stacktrace you provided does it seem to be caused by another expansion/plugin and not PlaceholderAPI directly:
`at me.thienbao860.expansion.spsexpansion.SpeedPerSecondExpansion.clear(SpeedPerSecondExpansion.java:121)`

The above line points to an expansion (SpeedPerSecond Expansion) which cancels a task ([Line 121](https://github.com/thienbao860/SpeedPerSec-Expansion/blob/master/src/me/thienbao860/expansion/spsexpansion/SpeedPerSecondExpansion.java#L121)) which seems to cause an NPE.
So it could be Bukkit not handling the cancelation of a Task properly, or the Expansion not doing stuff properly.

Anyway. Maybe a later build here has fixed this issue?

**Comment by RWoof** [comment]
> Hey.
> Looking at the stacktrace you provided does it seem to be caused by another expansion/plugin and not PlaceholderAPI directly:
> `at me.thienbao860.expansion.spsexpansion.SpeedPerSecondExpansion.clear(SpeedPerSecondExpansion.java:121)`
> 
> The above line points to an expansion (SpeedPerSecond Expansion) which cancels a task ([Line 121](https://github.com/thienbao860/SpeedPerSec-Expansion/blob/master/src/me/thienbao860/expansion/spsexpansion/SpeedPerSecondExpansion.java#L121)) which seems to cause an NPE.
> So it could be Bukkit not handling the cancelation of a Task properly, or the Expansion not doing stuff properly.
> 
> Anyway. Maybe a later build here has fixed this issue?

I tried with the most recent build as of today (108) and still get the same error when shutting down the server. I'm not sure why the SpeedPerSecond expansion isn't working? I unregistered the jar and then deleted it to get rid of the error for now. Thanks for helping me find the expansion that wasn't working!

**Comment by thienbao860** [comment]
Guess I will update it to compatible fully with new PAPI as well as that NPE

**Comment by thienbao860** [comment]
It is now updated. You can give it a try

**Comment by Andre601** [comment]
I will close this now as this was caused by an expansion it seems. Feel free to respond to this issue, if the same issue appears again without an expansion involved.
